### PR TITLE
Fix the Paint API explainer link

### PR DESCRIPTION
**Pull request by matt-oakes**

### CODE REVIEW

**Comment by surma** [comment]
Thank you! Would you mind fixing the link in `data.json` and running `npm run build` instead of fixing `index.html` manually?

**Comment by matt-oakes** [comment]
Whoops! Apologies, I edited this online directly and didn't see there was a json file. Sorry about that.

I'm getting a load of errors when I run the build (see below) and the index.html output has way more changes than I would expect. It might be easier for you to make the change yourself rather than for me to look into what's going on. I'll close this PR now 👍 

```
~/p/O/ishoudinireadyyet.com ❯❯❯ npm run build                                                                                             master ✱

> ishoudinireadyyet.com@0.1.0 build /Users/matt/projects/OS/ishoudinireadyyet.com
> node build.js

layout_safari: Error: ENOENT: no such file or directory, open 'partials/layout_safari.html'
layout_edge: Error: ENOENT: no such file or directory, open 'partials/layout_edge.html'
layout_opera: Error: ENOENT: no such file or directory, open 'partials/layout_opera.html'
layout_samsung: Error: ENOENT: no such file or directory, open 'partials/layout_samsung.html'
painting_edge: Error: ENOENT: no such file or directory, open 'partials/painting_edge.html'
painting_samsung: Error: ENOENT: no such file or directory, open 'partials/painting_samsung.html'
parser_safari: Error: ENOENT: no such file or directory, open 'partials/parser_safari.html'
parser_chrome: Error: ENOENT: no such file or directory, open 'partials/parser_chrome.html'
parser_edge: Error: ENOENT: no such file or directory, open 'partials/parser_edge.html'
parser_firefox: Error: ENOENT: no such file or directory, open 'partials/parser_firefox.html'
parser_opera: Error: ENOENT: no such file or directory, open 'partials/parser_opera.html'
parser_samsung: Error: ENOENT: no such file or directory, open 'partials/parser_samsung.html'
propertiesandvalues_edge: Error: ENOENT: no such file or directory, open 'partials/propertiesandvalues_edge.html'
propertiesandvalues_opera: Error: ENOENT: no such file or directory, open 'partials/propertiesandvalues_opera.html'
propertiesandvalues_samsung: Error: ENOENT: no such file or directory, open 'partials/propertiesandvalues_samsung.html'
animation_safari: Error: ENOENT: no such file or directory, open 'partials/animation_safari.html'
animation_edge: Error: ENOENT: no such file or directory, open 'partials/animation_edge.html'
animation_firefox: Error: ENOENT: no such file or directory, open 'partials/animation_firefox.html'
animation_opera: Error: ENOENT: no such file or directory, open 'partials/animation_opera.html'
animation_samsung: Error: ENOENT: no such file or directory, open 'partials/animation_samsung.html'
typedom_edge: Error: ENOENT: no such file or directory, open 'partials/typedom_edge.html'
typedom_samsung: Error: ENOENT: no such file or directory, open 'partials/typedom_samsung.html'
fontmetrics_safari: Error: ENOENT: no such file or directory, open 'partials/fontmetrics_safari.html'
fontmetrics_chrome: Error: ENOENT: no such file or directory, open 'partials/fontmetrics_chrome.html'
fontmetrics_edge: Error: ENOENT: no such file or directory, open 'partials/fontmetrics_edge.html'
fontmetrics_firefox: Error: ENOENT: no such file or directory, open 'partials/fontmetrics_firefox.html'
fontmetrics_opera: Error: ENOENT: no such file or directory, open 'partials/fontmetrics_opera.html'
fontmetrics_samsung: Error: ENOENT: no such file or directory, open 'partials/fontmetrics_samsung.html'
```

**Comment by surma** [comment]
Will do. Thanks for pinging!

**Comment by surma** [comment]
Fixed :)

**Pull request closed without merging**
