### PR TITLE
Update WebKit's Painting API status

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Painting API flag was added in [Safari Technology Preview 68](https://trac.webkit.org/changeset/237192/webkit) and updated later in versions [69](https://webkit.org/blog/8479/release-notes-for-safari-technology-preview-69/), [71](https://webkit.org/blog/8517/release-notes-for-safari-technology-preview-71/), [72](https://webkit.org/blog/8547/release-notes-for-safari-technology-preview-72/).

~~I'm not sure when exactly Typed OM was added, but it's available in "Experimental Features menu" in latest versions of Safari TP / Safari 12.1 Beta~~

### CODE REVIEW

**Comment by surma** [comment]
Yeah, I saw that, too, but none of the demos work currently. They error with a somewhat cryptic “global” error. So I was planning to only switch the flag once at least one of the demos work. I’ll keep this open until then. Thanks for doing the work!

screen shot 2019-02-27 at 10 46 39 am

**Comment by chicoxyzzy** [comment]
Fresh update. It's not enabled yet and it seems that it will be enabled just for GTK and WPE (WebKit for Embedded) soon.

ref: https://bugs.webkit.org/show_bug.cgi?id=192875#c3

**Comment by chicoxyzzy** [comment]
This one is not ready for merge yet

**Comment by chicoxyzzy** [comment]
fixed in #55

**Pull request closed without merging**
