### PR TITLE
Edge 79 release

### LINKED ISSUE #30: Update Edge support
Now that the chromium-based Edge browser has been released, does this mean the Edge column for support should flip over to look a little more like Chrome's column for support?

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Fixes https://github.com/surma/ishoudinireadyyet.com/issues/30

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
I can't find a good svg logo :( There is one on [Wikipedia page](https://en.wikipedia.org/wiki/Microsoft_Edge#/media/File:Microsoft_Edge_logo.svg) but in fact it's a base64 png

**Comment by chicoxyzzy** [comment]
Logo added!

**Comment by nucliweb** [comment]
👏🏼

**Comment by tomhodgins** [comment]
Thanks @chicoxyzzy 🙏 ❤️ 🤗

**Review by surma — APPROVED** [review]
Cheers mate!

**Comment by tomhodgins** [comment]
😘👌 Now that's a beautiful chart! Thanks

**Pull request merged**
