### PR TITLE
Update Chrome Properties and Values status

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Chrome 78 will be released today with Properties and Values support. ~~This change also removes "No support for `paint()` arguments, due to the lack of support for Properties and Values API." list item for Chrome Painting API details.~~

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
@surma ping 😇

**Comment by surma** [comment]
Sorry for not reacting sooner! Have you tested that arguments work for `paint()` in stable?

**Comment by chicoxyzzy** [comment]
No, I didn't TBH.

I've just tried examples from https://developer.mozilla.org/en-US/docs/Web/CSS/paint#Examples and it seems that arguments for `paint()` still doesn't work in Chrome 78. I'll update the PR.

**Comment by surma** [comment]
Cc @flackr

**Pull request merged**
