### PR TITLE
Fetch the browser logos using `npm`

### PR DESCRIPTION
**Pull request by alrra**
The [browser logos](https://github.com/alrra/browser-logos) are available on [`npm`](https://www.npmjs.com/org/browser-logos). They are usually keep up to date and highly optimized (e.g. see the changelogs for [`Firefox`](https://github.com/alrra/browser-logos/blob/180f2c33c07e83645fa64ea6097f0aa9d1fadd58/src/firefox/CHANGELOG.md), [`Chrome`](https://github.com/alrra/browser-logos/blob/180f2c33c07e83645fa64ea6097f0aa9d1fadd58/src/chrome/CHANGELOG.md), etc.).

---

@surma I didn't wanted to modify too much of the unrelated code, so let me know if I missed anything, or you want me to change something.

### CODE REVIEW

**Comment by alrra** [comment]
| Before | After |
|:---|:---|
|  |  |

**Review by surma — APPROVED** [review]
I dig it. Thanks a bunch.

**Comment by alrra** [comment]
@surma I don't know how things are set up on the server, but did you run `npm install` at least once? The images are currently [missing on the live site](https://ishoudinireadyyet.com/).

**Comment by surma** [comment]
Ah we shouldn’t have ignored the files. This setup used GH pages currently.

**Comment by surma** [comment]
Alright it’s fixed. I should really move this setup to Netlify 🤔

**Comment by alrra** [comment]
> Alright it’s fixed. 

👍

**Pull request merged**
